export const ENV_DATABASE_TYPE = 'DATABASE_TYPE';
export const ENV_DATABASE_HOST = 'DATABASE_HOST';
export const ENV_DATABASE_PORT = 'DATABASE_PORT';
export const ENV_DATABASE_NAME = 'DATABASE_NAME';
export const ENV_DATABASE_USERNAME = 'DATABASE_USERNAME';
export const ENV_DATABASE_PASSWORD = 'DATABASE_PASSWORD';
